import { useState } from 'react'
import { useTranslation } from 'react-i18next'

import Dialog from '@/components/ui/Dialog'
import FormField from '@/components/forms/FormField'
import FormActions from '@/components/forms/FormActions'
import Input from '@/components/ui/Input'
import Select from '@/components/ui/Select'

export interface StockTransferFormProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onSubmit: (input: Record<string, unknown>) => void
  warehouses: Array<{ _id: string; name: string }>
}

export function StockTransferForm({
  open,
  onOpenChange,
  onSubmit,
  warehouses,
}: StockTransferFormProps) {
  const { t } = useTranslation('inventory')

  const [code, setCode] = useState('')
  const [fromWarehouseId, setFromWarehouseId] = useState('')
  const [toWarehouseId, setToWarehouseId] = useState('')
  const [notes, setNotes] = useState('')
  const [expectedArrivalDate, setExpectedArrivalDate] = useState('')
  const [errors, setErrors] = useState<Record<string, string>>({})

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {}
    if (!code.trim()) newErrors.code = 'Required'
    if (!fromWarehouseId) newErrors.fromWarehouseId = 'Required'
    if (!toWarehouseId) newErrors.toWarehouseId = 'Required'
    if (fromWarehouseId && toWarehouseId && fromWarehouseId === toWarehouseId) {
      newErrors.toWarehouseId = t('stockTransfer.sameWarehouse')
    }
    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = () => {
    if (!validate()) return
    onSubmit({
      code: code.trim() || undefined,
      fromWarehouseId,
      toWarehouseId,
      notes: notes.trim() || undefined,
      expectedArrivalDate: expectedArrivalDate || undefined,
    })
    onOpenChange(false)
  }

  return (
    <Dialog
      open={open}
      onOpenChange={onOpenChange}
      title={t('stockTransfer.create')}
      size="lg"
      footer={
        <FormActions
          submitLabel={t('stockTransfer.create')}
          onCancel={() => onOpenChange(false)}
          onSubmit={handleSubmit}
        />
      }
    >
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <FormField label={t('stockTransfer.code')} required error={errors.code}>
          <Input
            value={code}
            onChange={(e) => setCode(e.target.value)}
            placeholder={t('stockTransfer.autoGenerated')}
          />
        </FormField>
        <FormField label={t('stockTransfer.expectedArrivalDate')}>
          <Input
            type="date"
            value={expectedArrivalDate}
            onChange={(e) => setExpectedArrivalDate(e.target.value)}
          />
        </FormField>
        <FormField label={t('stockTransfer.fromWarehouse')} required error={errors.fromWarehouseId}>
          <Select value={fromWarehouseId} onChange={(e) => setFromWarehouseId(e.target.value)}>
            <option value="">{t('stockTransfer.selectWarehouse')}</option>
            {warehouses.map((wh) => (
              <option key={wh._id} value={wh._id}>
                {wh.name}
              </option>
            ))}
          </Select>
        </FormField>
        <FormField label={t('stockTransfer.toWarehouse')} required error={errors.toWarehouseId}>
          <Select value={toWarehouseId} onChange={(e) => setToWarehouseId(e.target.value)}>
            <option value="">{t('stockTransfer.selectWarehouse')}</option>
            {warehouses.map((wh) => (
              <option key={wh._id} value={wh._id}>
                {wh.name}
              </option>
            ))}
          </Select>
        </FormField>
        <FormField label={t('stockTransfer.notes')} className="sm:col-span-2">
          <Input value={notes} onChange={(e) => setNotes(e.target.value)} />
        </FormField>
      </div>
    </Dialog>
  )
}

export default StockTransferForm
